wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.0
    start_time: 1662721699.596557
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 14
      - 16
      - 23
      - 24
      4: 3.7.0
      5: 0.13.1
      8:
      - 5
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 30
